language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
before_install:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/test.sh
script:
  - ./scripts/build.sh --quiet verify
  - ./scripts/test.sh --quiet verify