language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
before_install:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/test.sh
script:
  - cd ./scripts && ./build.sh --quiet verify
  - cd ./scripts && ./test.sh --quiet verify