language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
before_install:
  - chmod +x build.sh
  - chmod +x test.sh
script:
  - ./build.sh --quiet verify
  - ./test.sh --quiet verify