language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./src/Ether.Network/Ether.Network.csproj -f netstandard2.0
  - dotnet test ./test/Ether.Network.Tests/Ether.Network.Tests.csproj